name: LiarGame
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: xcconfig/Project-Debug.xcconfig
  Release: xcconfig/Project-Release.xcconfig

packages:
  Then:
    url: https://github.com/devxoul/Then
    from: 2.7.0
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    from: 6.5.0
  RxCocoa:
    url: https://github.com/ReactiveX/RxSwift
    from: 6.5.0
  RxRelay:
    url: https://github.com/ReactiveX/RxSwift
    from: 6.5.0
  ReactorKit:
    url: https://github.com/ReactorKit/ReactorKit
    from: 3.2.0
  PinLayout:
    url: https://github.com/layoutBox/PinLayout
    from: 1.9.4
  FlexLayout:
    url: https://github.com/layoutBox/FlexLayout
    from: 1.3.18

targets:
  LiarGame:
    type: application
    platform: iOS

    deploymentTarget: "13.0"

    configFiles:
      Debug: xcconfig/LiarGame-Debug.xcconfig
      Release: xcconfig/LiarGame-Release.xcconfig

    sources: [LiarGame]
    settings:
      base:
        INFOPLIST_FILE: LiarGame/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: Jay.LiarGameme

    dependencies:
      - package: Then
      - package: RxSwift
      - package: RxCocoa
      - package: RxRelay
      - package: ReactorKit
      - package: PinLayout
      - package: FlexLayout
      - framework: frameworks/YouTubeiOSPlayerHelper.xcframework
