name: GameBundle
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: xcconfig/Project-Debug.xcconfig
  Release: xcconfig/Project-Release.xcconfig

options:
  indentWidth: 2
  tabWidth: 2

packages:
  Then:
    url: https://github.com/devxoul/Then
    # version: 2.7.0
    revision: d41ef523faef0f911369f79c0b96815d9dbb6d7a
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    version: 6.5.0
  ReactorKit:
    url: https://github.com/ReactorKit/ReactorKit
    version: 3.2.0
  PinLayout:
    url: https://github.com/layoutBox/PinLayout
    version: 1.10.2
  FlexLayout:
    url: https://github.com/layoutBox/FlexLayout
    version: 1.3.24
  Lottie:
    url: https://github.com/airbnb/lottie-ios
    version: 3.3.0
  Pure:
    url: https://github.com/devxoul/Pure
    version: 1.1.4

targets:
  GameBundle:
    type: application
    platform: iOS
    deploymentTarget: "15.2"

    configFiles:
      Debug: xcconfig/GameBundle-Debug.xcconfig
      Release: xcconfig/GameBundle-Release.xcconfig

    sources: [Targets/GameBundle]
    settings:
      base:
        INFOPLIST_FILE: Targets/GameBundle/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: Jay.LiarGamem

    dependencies:
      - target: LiarGame
      - target: Home
      - target: RandomMusic
      - target: UtilKit
      - package: Then
      - package: RxSwift
        product: RxSwift
      - package: RxSwift
        product: RxCocoa
      - package: RxSwift
        product: RxRelay
      - package: ReactorKit
      - package: PinLayout
      - package: FlexLayout
      - package: Lottie
      - package: Pure
        product: Pure
      - framework: frameworks/YouTubeiOSPlayerHelper.xcframework
    preBuildScripts:
      - path: scripts/swiftformat.sh
        name: Swift Format
      - path: scripts/swiftlint.sh
        name: Swift Lint

  Home:
    type: framework.static
    platform: iOS
    deploymentTarget: "15.2"
    info:
      path: Targets/Home/Resources/Info.plist
    configFiles:
      Debug: xcconfig/GameBundle-Debug.xcconfig
      Release: xcconfig/GameBundle-Release.xcconfig
    sources: [Targets/Home]
    dependencies:
      - target: UtilKit
      - target: RandomMusic
      - target: LiarGame
      - package: Then
      - package: RxSwift
        product: RxSwift
      - package: RxSwift
        product: RxCocoa
      - package: RxSwift
        product: RxRelay
      - package: ReactorKit
      - package: PinLayout
      - package: FlexLayout
      - package: Pure
    preBuildScripts:
      - path: scripts/swiftformat.sh
        name: Swift Format
      - path: scripts/swiftlint.sh
        name: Swift Lint

  LiarGame:
    type: framework.static
    platform: iOS
    deploymentTarget: "15.2"
    info:
      path: Targets/LiarGame/Resources/Info.plist
    configFiles:
      Debug: xcconfig/GameBundle-Debug.xcconfig
      Release: xcconfig/GameBundle-Release.xcconfig
    sources: [Targets/LiarGame]
    dependencies:
      - target: UtilKit
      - package: Then
      - package: RxSwift
        product: RxSwift
      - package: RxSwift
        product: RxCocoa
      - package: RxSwift
        product: RxRelay
      - package: ReactorKit
      - package: PinLayout
      - package: FlexLayout
      - package: Pure
    preBuildScripts:
      - path: scripts/swiftformat.sh
        name: Swift Format
      - path: scripts/swiftlint.sh
        name: Swift Lint

  RandomMusic:
    type: framework.static
    platform: iOS
    deploymentTarget: "15.2"
    info:
      path: Targets/RandomMusic/Resources/Info.plist
    configFiles:
      Debug: xcconfig/GameBundle-Debug.xcconfig
      Release: xcconfig/GameBundle-Release.xcconfig
    sources: [Targets/RandomMusic]
    dependencies:
      - target: UtilKit
      - package: Pure
      - package: Then
      - package: RxSwift
        product: RxSwift
      - package: RxSwift
        product: RxCocoa
      - package: RxSwift
        product: RxRelay
      - package: ReactorKit
      - package: PinLayout
      - package: FlexLayout
      - package: Lottie
      - framework: frameworks/YouTubeiOSPlayerHelper.xcframework
    preBuildScripts:
      - path: scripts/swiftformat.sh
        name: Swift Format
      - path: scripts/swiftlint.sh
        name: Swift Lint

  UtilKit:
    type: framework.static
    platform: iOS
    info:
      path: Targets/UtilKit/Resources/Info.plist
    configFiles:
      Debug: xcconfig/GameBundle-Debug.xcconfig
      Release: xcconfig/GameBundle-Release.xcconfig
    sources: [Targets/UtilKit]
    dependencies:
      - package: FlexLayout
    preBuildScripts:
      - path: scripts/swiftformat.sh
        name: Swift Format
      - path: scripts/swiftlint.sh
        name: Swift Lint
