name: LiarGame
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: xcconfig/Project-Debug.xcconfig
  Release: xcconfig/Project-Release.xcconfig

options:
  indentWidth: 2
  tabWidth: 2

packages:
  Then:
    url: https://github.com/devxoul/Then
    # version: 2.7.0
    revision: d41ef523faef0f911369f79c0b96815d9dbb6d7a
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    version: 6.5.0
  ReactorKit:
    url: https://github.com/ReactorKit/ReactorKit
    version: 3.2.0
  PinLayout:
    url: https://github.com/layoutBox/PinLayout
    version: 1.10.2
  FlexLayout:
    url: https://github.com/layoutBox/FlexLayout
    version: 1.3.24
  Lottie:
    url: https://github.com/airbnb/lottie-ios
    version: 3.3.0

targets:
  LiarGame:
    type: application
    platform: iOS

    deploymentTarget: "13.0"

    configFiles:
      Debug: xcconfig/LiarGame-Debug.xcconfig
      Release: xcconfig/LiarGame-Release.xcconfig

    sources: [LiarGame]
    settings:
      base:
        INFOPLIST_FILE: LiarGame/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: Jay.LiarGameme

    dependencies:
      - package: Then
      - package: RxSwift
        product: RxSwift
      - package: RxSwift
        product: RxCocoa
      - package: RxSwift
        product: RxRelay
      - package: ReactorKit
      - package: PinLayout
      - package: FlexLayout
      - package: Lottie
      - framework: frameworks/YouTubeiOSPlayerHelper.xcframework
    preBuildScripts:
      - path: scripts/swiftformat.sh
        name: Swift Format
      - path: scripts/swiftlint.sh
        name: Swift Lint
